from NeatPrint import neatPrintTable
		
MAKECONNECT URL jdbc:oracle:thin:@rising-sun.microlab.cs.utexas.edu:1521:orcl UNAME CS345_ecp456 PWORD orcl_ecp456 CONTYPE local;

# !!! need to run tests/fillTestTables.py before running this
#output=SELECT TIME TIME_1, p.PRICE, p.VETID AS VETID_P, p.PETID FROM VISITS AS p WHERE PRICE = 80; #works
#neatPrintTable(output);

#output=SELECT * FROM VISITS; #works
#neatPrintTable(output);
#output=SELECT PETS.NAME, PETS.TYPEID FROM PETS	WHERE PETS.TYPEID = (SELECT	PETS.TYPEID	FROM PETS WHERE	PETS.BIRTH_YEAR	= (SELECT PETS.BIRTH_YEAR FROM PETS	WHERE PETS.PETID = 1001));
#output=SELECT NAME FROM VETS WHERE VETS.VETID = (SELECT VISITS.VETID FROM VISITS WHERE VISITS.VETID = (SELECT VETS.VETID FROM VETS WHERE VETS.VETID = 4001));
#output=SELECT VETID, NAME FROM VETS WHERE VETID = 4001; # = (SELECT VETID FROM VISITS WHERE VETS.VETID = 4001);

# ours is working
#output=SELECT NAME FROM VETS WHERE VETID = (SELECT VETID FROM VISITS WHERE PETID = 1001); 

# ours is working
#output=SELECT * FROM VETS WHERE VETID = (SELECT VETID FROM VISITS WHERE PETID = (SELECT PETID FROM PETS WHERE NAME = 'NEMO')); 

#output=SELECT * FROM PETS	WHERE PETS.TYPEID = (SELECT	PETS.TYPEID	FROM PETS WHERE	PETS.BIRTH_YEAR	= (SELECT PETS.BIRTH_YEAR FROM PETS WHERE PETS.PETID = 1001));

output=SELECT * FROM PETS WHERE PETS.TYPEID = (SELECT ANIMALTYPES.TYPEID FROM ANIMALTYPES WHERE ANIMALTYPES.SPECIES = 'CAT');

#output=SELECT * FROM PETS, VETS WHERE PRICE = (SELECT PRICE FROM VISITS WHERE PETID = 1006); #works
#neatPrintTable(output);
#output=SELECT NAME FROM VETS WHERE HIRED_YEAR = 2011;
#output= SELECT PETS.NAME, PETS.TYPEID FROM PETS WHERE PETS.PETID = (SELECT PETS.PETID FROM PETS WHERE PETS.PETID = 1001);
#output= SELECT PETS.NAME, PETS.TYPEID FROM PETS WHERE PETS.PETID = (SELECT PETS.PETID FROM PETS WHERE PETS.PETID = (SELECT PETS.PETID FROM PETS WHERE PETS.PETID = 1001));

#output=SELECT * FROM VISITS WHERE VETID = (SELECT VETID FROM VISITS WHERE VETID = (SELECT VETID FROM VETS WHERE NAME = 'BOBBY'));

neatPrintTable(output);


#output=SELECT VETS.NAME FROM VETS WHERE VETS.HIRED_YEAR = 2011;
#output=SELECT * FROM VISITS WHERE VETID = (SELECT VETID FROM VETS WHERE HIRED_YEAR = 2011);
#output=SELECT ANIMALTYPES.TYPEID FROM ANIMALTYPES WHERE ANIMALTYPES.SPECIES = 'CAT';
#output=SELECT * FROM ANIMALTYPES;
#output=SELECT SPECIES FROM ANIMALTYPES WHERE ANIMALTYPES.SPECIES = "CAT";
#output=SELECT * FROM PETS WHERE PETS.TYPEID = (SELECT ANIMALTYPES.TYPEID FROM ANIMALTYPES WHERE ANIMALTYPES.SPECIES = "CAT");  #(SELECT PRICE FROM VISITS WHERE PETID = 1006); #works

#output=SELECT * FROM PETS, VETS WHERE PRICE = (SELECT PRICE FROM VISITS WHERE VISITS.PETID = 1006); #works
#print  output
#neatPrintTable(output);

#output=SELECT TIME, PRICE, VETID, PETID FROM VISITS WHERE PRICE = 80; #works
#neatPrintTable(output);

