from NeatPrint import neatPrintTable

MAKECONNECT URL jdbc:oracle:thin:@rising-sun.microlab.cs.utexas.edu:1521:orcl UNAME CS345_demo PWORD orcl_demo CONTYPE local;

# !!! need to run tests/smallFillTestTables.py before running this

output=SELECT * FROM PETS; #works
neatPrintTable(output);

output=SELECT PETS.NAME, PETS.BIRTH_YEAR FROM PETS ORDER BY PETS.BIRTH_YEAR DESC;
neatPrintTable(output);

output=SELECT PETS.NAME, ANIMALTYPES.SPECIES FROM PETS JOIN ANIMALTYPES ON PETS.TYPEID = ANIMALTYPES.TYPEID;
neatPrintTable(output);

output=SELECT PETS.NAME, PETS.PETID, PETS.BIRTH_YEAR, ANIMALTYPES.SPECIES FROM PETS JOIN ANIMALTYPES ON PETS.TYPEID = ANIMALTYPES.TYPEID WHERE PETS.BIRTH_YEAR = 2009;
neatPrintTable(output);

output=SELECT PETS.NAME, PETS.PETID, PETS.BIRTH_YEAR, ANIMALTYPES.SPECIES FROM PETS JOIN ANIMALTYPES ON PETS.TYPEID = ANIMALTYPES.TYPEID WHERE PETS.BIRTH_YEAR < 2007 AND PETS.PETID = 1001 ORDER BY ANIMALTYPES.TYPEID DESC;
neatPrintTable(output);

output=SELECT PETS.NAME, PETS.PETID, PETS.BIRTH_YEAR FROM PETS WHERE PETS.BIRTH_YEAR = 2009;
neatPrintTable(output);
