def neatPrint(results):
        for ii in range(0, len(results)):
                print(results[ii]);
        print;

MAKECONNECT URL jdbc:oracle:thin:@rising-sun.microlab.cs.utexas.edu:1521:orcl UNAME CS345_demo PWORD orcl_demo CONTYPE remote;
output = (SELECT TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME = "RDF_DATA_TABLE";)
neatPrint(output);

#This drops the RDF_DATA_TABLE and RDF_MODEL_userName
MAKECONNECT URL jdbc:oracle:thin:@rising-sun.microlab.cs.utexas.edu:1521:orcl UNAME CS345_demo PWORD orcl_demo CONTYPE local;
#if len(output) == 2:
#	DROP TABLE RDF_DATA;

DROP TABLE RDF_DATA;

MAKECONNECT URL jdbc:oracle:thin:@rising-sun.microlab.cs.utexas.edu:1521:orcl UNAME CS345_demo PWORD orcl_demo CONTYPE local;

CREATE TABLE PETS (PETID NUMERIC, NAME VARCHAR2(30), TYPEID NUMERIC, BIRTH_YEAR NUMERIC);
INSERT INTO PETS (PETID, NAME, TYPEID, BIRTH_YEAR) VALUES (1001, 'COUSCOUS',	2001, 2005);
INSERT INTO PETS (PETID, NAME, TYPEID, BIRTH_YEAR) VALUES (1002, 'PUMPKIN',	2001, 2009);
INSERT INTO PETS (PETID, NAME, TYPEID, BIRTH_YEAR) VALUES (1003, 'MAPLE',	2001, 2009);
INSERT INTO PETS (PETID, NAME, TYPEID, BIRTH_YEAR) VALUES (1004, 'MIKE',	2002, 2007);
INSERT INTO PETS (PETID, NAME, TYPEID, BIRTH_YEAR) VALUES (1005, 'BARKLY',	2002, 2000);
INSERT INTO PETS (PETID, NAME, TYPEID, BIRTH_YEAR) VALUES (1006, 'NEMO',	2002, 2010);
INSERT INTO PETS (PETID, NAME, TYPEID, BIRTH_YEAR) VALUES (1007, 'JERRY',	2003, 2006);

CREATE TABLE ANIMALTYPES (TYPEID NUMERIC, SPECIES VARCHAR2);
INSERT INTO ANIMALTYPES (TYPEID, SPECIES) VALUES (2001, 'CAT');
INSERT INTO ANIMALTYPES (TYPEID, SPECIES) VALUES (2002, 'DOG');
INSERT INTO ANIMALTYPES (TYPEID, SPECIES) VALUES (2003, 'RABBIT');

